on:
  push:
    branches:
      - main

jobs:
  run:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Packages
        run: npm ci

      - name: Test
        run: |
          npm run lint

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_USER }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_USER }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: npx semantic-release
